<a href="https://colab.research.google.com/github/satwika06bhaskar-design/DATA-SCIENCE-30172/blob/main/LABS/WEEK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Regression Models for Predictive Analytics
# Application: House Price Prediction and House Purchase Classification

import numpy as np
from sklearn.linear_model import LinearRegression, LogisticRegression

# LINEAR REGRESSION
print("----- Linear Regression -----")
# Independent Variable (House Size in square feet)
X_linear = np.array([[1000], [1200], [1500], [1800], [2000]])
# Dependent Variable (House Price in lakhs)
y_linear = np.array([50, 55, 65, 80, 90])
# Create Linear Regression model
linear_model = LinearRegression()
# Train model
linear_model.fit(X_linear, y_linear)
# Predict price for new house
new_house_size = np.array([[1700]])
predicted_price = linear_model.predict(new_house_size)
print("Training House Sizes:")
print(X_linear.flatten())
print("\nTraining House Prices:")
print(y_linear)
print("\nPredicted Price for 1700 sq.ft house:")
print(predicted_price[0])
# ---------------------------------------------------
# LOGISTIC REGRESSION
# ---------------------------------------------------
print("\n\n----- Logistic Regression -----")
# Independent Variable (House Price in lakhs)
X_logistic = np.array([[40], [50], [60], [70], [80], [90]])

# Dependent Variable
# 0 = Not Purchased
# 1 = Purchased
y_logistic = np.array([0, 0, 0, 1, 1, 1])
# Create Logistic Regression model
logistic_model = LogisticRegression()
# Train model
logistic_model.fit(X_logistic, y_logistic)
# Predict whether customer will purchase
test_price = np.array([[75]])
purchase_prediction = logistic_model.predict(test_price)
# Probability prediction
purchase_probability = logistic_model.predict_proba(test_price)
print("Training House Prices:")
print(X_logistic.flatten())
print("\nPurchase Labels:")
print(y_logistic)
print("\nTest House Price:", test_price[0][0])
print("\nPurchase Prediction:")
print(purchase_prediction[0])
print("\nPrediction Probabilities:")
print(purchase_probability)


----- Linear Regression -----
Training House Sizes:
[1000 1200 1500 1800 2000]

Training House Prices:
[50 55 65 80 90]

Predicted Price for 1700 sq.ft house:
76.08823529411764


----- Logistic Regression -----
Training House Prices:
[40 50 60 70 80 90]

Purchase Labels:
[0 0 0 1 1 1]

Test House Price: 75

Purchase Prediction:
1

Prediction Probabilities:
[[0.00349394 0.99650606]]


In [ ]:
# Statistical Hypothesis Testing
# 1. Z-Test
# 2. Independent t-Test
# Application: Student Performance Analysis
import numpy as np
from scipy import stats
from statsmodels.stats.weightstats import ztest

# Z-TEST
print("----- Z-Test -----")
# Sample marks of students
sample_marks = np.array([78, 82, 85, 88, 90, 76, 95, 89, 84, 91])
# Population mean
population_mean = 80
# Perform one-sample Z-test
z_stat, p_value = ztest(sample_marks, value=population_mean)
print("Sample Marks:")
print(sample_marks)
print("\nPopulation Mean:", population_mean)
print("\nZ-Statistic:", z_stat)
print("P-Value:", p_value)
# Decision
alpha = 0.05
if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")
# INDEPENDENT t-TEST
print("\n\n----- Independent t-Test -----")
# Marks of two different classes
class_A = np.array([78, 82, 85, 88, 90])
class_B = np.array([72, 75, 70, 68, 74])
# Perform independent t-test
t_stat, p_value = stats.ttest_ind(class_A, class_B)
print("Class A Marks:")
print(class_A)
print("\nClass B Marks:")
print(class_B)
print("\nt-Statistic:", t_stat)
print("P-Value:", p_value)
# Decision
if p_value < alpha:
    print("\nResult: Reject Null Hypothesis")
else:
    print("\nResult: Fail to Reject Null Hypothesis")


----- Z-Test -----
Sample Marks:
[78 82 85 88 90 76 95 89 84 91]

Population Mean: 80

Z-Statistic: 3.0778387488959273
P-Value: 0.0020850770735042832

Result: Reject Null Hypothesis


----- Independent t-Test -----
Class A Marks:
[78 82 85 88 90]

Class B Marks:
[72 75 70 68 74]

t-Statistic: 5.140603704975992
P-Value: 0.000884475345807384

Result: Reject Null Hypothesis
